-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 21:08:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smartmsph
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smartmsph
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartmsph` DEFAULT CHARACTER SET utf8 ;
USE `smartmsph` ;

-- -----------------------------------------------------
-- Table `smartmsph`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`person` (
  `Person_Id` BIGINT NOT NULL,
  `Name` VARCHAR(50) NOT NULL,
  `LastName1` VARCHAR(50) NOT NULL,
  `LastName2` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(50) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Person_Id`),
  UNIQUE INDEX `id_UNIQUE` (`Person_Id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`department` (
  `Department_Id` SMALLINT NOT NULL,
  `DepartmentName` VARCHAR(45) NOT NULL,
  `Person_Id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`Department_Id`),
  UNIQUE INDEX `id_UNIQUE` (`Department_Id` ASC) VISIBLE,
  UNIQUE INDEX `DepartmentName_UNIQUE` (`DepartmentName` ASC) VISIBLE,
  INDEX `fk_Department_Person1_idx` (`Person_Id` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Person1`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `smartmsph`.`person` (`Person_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`role` (
  `Role_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`user` (
  `User_Id` SMALLINT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Person_id` BIGINT NULL DEFAULT NULL,
  `Role_id` SMALLINT NOT NULL,
  `department_id` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`User_Id`),
  UNIQUE INDEX `id_UNIQUE` (`User_Id` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE,
  INDEX `fk_citizen_user_citizen1_idx` (`Person_id` ASC) VISIBLE,
  INDEX `fk_User_Role1_idx` (`Role_id` ASC) VISIBLE,
  INDEX `fk_department_user_department_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_department_user_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `smartmsph`.`department` (`Department_Id`),
  CONSTRAINT `fk_person_user_Person`
    FOREIGN KEY (`Person_id`)
    REFERENCES `smartmsph`.`person` (`Person_Id`),
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_id`)
    REFERENCES `smartmsph`.`role` (`Role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`complain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`complain` (
  `Complain_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(200) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `Person_Id` BIGINT NULL DEFAULT NULL,
  `User_id` SMALLINT NULL DEFAULT NULL,
  `employee` VARCHAR(45) NOT NULL,
  `employee_department` VARCHAR(45) NULL DEFAULT NULL,
  `Department_Id` SMALLINT NULL DEFAULT NULL,
  PRIMARY KEY (`Complain_id`),
  INDEX `fk_complain_citizen1_idx` (`Person_Id` ASC) VISIBLE,
  INDEX `fk_complain_department1_idx` (`Department_Id` ASC) VISIBLE,
  INDEX `fk_User_complain1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_complain_department1`
    FOREIGN KEY (`Department_Id`)
    REFERENCES `smartmsph`.`department` (`Department_Id`),
  CONSTRAINT `fk_complain_Person`
    FOREIGN KEY (`Person_Id`)
    REFERENCES `smartmsph`.`person` (`Person_Id`),
  CONSTRAINT `fk_User_complain1`
    FOREIGN KEY (`User_id`)
    REFERENCES `smartmsph`.`user` (`User_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`ticket` (
  `Ticket_id` SMALLINT NOT NULL auto_increment,
  `Department_id` SMALLINT NULL DEFAULT NULL,
  `Ticketcol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Ticket_id`),
  INDEX `fk_ticket_department1_idx` (`Department_id` ASC) VISIBLE,
  CONSTRAINT `fk_ticket_department1`
    FOREIGN KEY (`Department_id`)
    REFERENCES `smartmsph`.`department` (`Department_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`denounces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`denounces` (
  `Denounces_id` SMALLINT NOT NULL auto_increment,
  `Description` VARCHAR(3999) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `Ticket_id` SMALLINT NULL DEFAULT NULL,
  `Person_id` BIGINT NULL DEFAULT NULL,
  `User_id` SMALLINT NULL DEFAULT NULL,
  `Department_id` SMALLINT NULL DEFAULT NULL,
  `Photo` MEDIUMTEXT NULL DEFAULT NULL,
  `Latitud` VARCHAR(100) NULL DEFAULT NULL,
  `Longitud` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Denounces_id`),
  INDEX `fk_denounces_ticket1_idx` (`Ticket_id` ASC) VISIBLE,
  INDEX `fk_denounces_citizen1_idx` (`Person_id` ASC) VISIBLE,
  INDEX `fk_User_denounces_idx` (`User_id` ASC) VISIBLE,
   INDEX `fk_Department_denounces_idx` (`Department_id` ASC) VISIBLE,
  CONSTRAINT `fk_denounces_person`
    FOREIGN KEY (`Person_id`)
    REFERENCES `smartmsph`.`person` (`Person_Id`),
  CONSTRAINT `fk_denounces_ticket1`
    FOREIGN KEY (`Ticket_id`)
    REFERENCES `smartmsph`.`ticket` (`Ticket_id`),
  CONSTRAINT `fk_User_Denounces`
    FOREIGN KEY (`User_id`)
    REFERENCES `smartmsph`.`user` (`User_Id`),
      CONSTRAINT `fk_denounces_department1`
    FOREIGN KEY (`Department_Id`)
    REFERENCES `smartmsph`.`department` (`Department_Id`))
    
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartmsph`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartmsph`.`news` (
  `News_Id` SMALLINT NOT NULL AUTO_INCREMENT,
  `descri` VARCHAR(1000) NOT NULL,
  `photo` MEDIUMTEXT   NOT NULL,
  `titulo` VARCHAR(200) NULL,
  PRIMARY KEY (`News_Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `smartmsph` ;

-- -----------------------------------------------------
-- procedure UsuarioRegistro
-- -----------------------------------------------------

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UsuarioRegistro`(Ppersona_id bigint, Pnombre varchar(100), Papellido1 varchar(100),
Papellido2 varchar(100),Pcorreo varchar(100), Ptelefono varchar(100), Pusuario_Id smallint, PnombreUsuario varchar(100),
Ppassword varchar(100), Prole smallint  
)
BEGIN
insert into person values(Ppersona_id,Pnombre,Papellido1,Papellido2,Pcorreo,Ptelefono);

insert into user select MAX(User_Id) + 1 
,PnombreUsuario
,Ppassword
,Ppersona_id
,Prole
,null 
from user; 

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure VerifyCredentials
-- -----------------------------------------------------

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `VerifyCredentials`( IN Puser varchar(45), IN Ppassword varchar(45))
BEGIN

SELECT a.*,b.Name,b.LastName1,b.LastName2,b.Email,b.phoneNumber,c.DepartmentName
FROM user a 
JOIN person b ON a.Person_Id=b.Person_Id
LEFT JOIN department c ON a.department_id = c.Department_Id
 where a.UserName=Puser and a.Password = Ppassword;

END$$
DROP PROCEDURE IF EXISTS NewInsert;
DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `NewInsert`(Pdescripcion varchar(10000), Pphoto MEDIUMTEXT, Ptitulo varchar(10000))
BEGIN
insert into  news(descri,photo,titulo) values(Pdescripcion,Pphoto,Ptitulo);
END$$

DELIMITER ;

DROP PROCEDURE IF EXISTS TodoDepartamento;
DELIMITER $$
USE `smartmsph`$$
CREATE PROCEDURE `TodoDepartamento` ()
BEGIN
SELECT * FROM smartmsph.department;
END$$

DELIMITER ;


DROP PROCEDURE IF EXISTS FuncioXDeparta;
DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `FuncioXDeparta`( IN Pdepa SMALLINT)
BEGIN
SELECT p.Name , p.LastName1, p.LastName2, p.Person_Id
FROM smartmsph.user u
INNER JOIN  smartmsph.person p
where u.department_id=Pdepa and p.Person_Id=u.Person_id ;
END$$
DELIMITER ;


DROP procedure IF EXISTS `ComplainInsert`;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ComplainInsert`(PDescription varchar(200), Pstate varchar(45), PPerson_Id bigint,PUser_id smallint,Pemployee varchar(45),Pemployee_department varchar(45),PDepartment_Id smallint)
BEGIN
INSERT INTO complain (Description, state, Person_Id, User_id, employee, employee_department, Department_Id) VALUES (PDescription, Pstate, PPerson_Id, PUser_id, Pemployee, Pemployee_department, PDepartment_Id);
END$$

DROP procedure IF EXISTS `ObtainTicket`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ObtainTicket`(IN PDepartment_id SMALLINT,PTicketcol varchar(45))
BEGIN
INSERT INTO ticket (Department_id,Ticketcol) VALUES (PDepartment_id,PTicketcol);
SELECT * FROM smartmsph.ticket WHERE Ticket_id = (SELECT MAX(Ticket_id) FROM smartmsph.ticket);
END$$
DELIMITER ;

DROP procedure IF EXISTS `SaveDenounce`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `SaveDenounce`(PDescription varchar(3999), Pstate varchar(45), PTicket_id smallint,PPerson_id bigint,PUser_id smallint,PDepartment_id smallint,PPhoto MEDIUMTEXT,PLatitud varchar(100),PLongitud varchar(100))
BEGIN
INSERT INTO denounces (Description, State, Ticket_id, Person_id, User_id, Department_id, Photo, Latitud, Longitud) VALUES (PDescription,Pstate,PTicket_id,PPerson_id,PUser_id,PDepartment_id,PPhoto,PLatitud,PLongitud);
END$$
DELIMITER ;

DROP procedure IF EXISTS `ObtainNews`;
DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ObtainNews`()
BEGIN
SELECT * FROM smartmsph.news;
END$$
DELIMITER ;	


-- lo de tony

-- -----------------------------------------------------
-- procedure DepartamentoRegistro
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`DepartamentoRegistro`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DepartamentoRegistro`(
  `PDepartment_Id` SMALLINT(20),
  `PDepartmentName` VARCHAR(45),
  `PPerson_Id` BIGINT(20)
)
BEGIN

INSERT INTO `department` values (`PDepartment_Id`, `PDepartmentName`,`PPerson_Id`);

END$$
DELIMITER ;
-- -----------------------------------------------------
-- procedure addUser
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`addUser`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `addUser`(
  IN`PUser_Id` SMALLINT(20),
  IN`PUserName` VARCHAR(45),
  IN`PPassword` VARCHAR(45),
  IN`PPerson_id` BIGINT(20),
  IN`PRole_id` SMALLINT(6),
  IN`Pdepartment_id` SMALLINT(6)
  )
BEGIN

INSERT INTO user(User_Id,UserName,Password,Person_id,Role_id,department_id)
 values(PUser_Id,PUserName,PPassword,PPerson_id,PRole_id,Pdepartment_id);

END$$
DELIMITER ;
-- -----------------------------------------------------
-- procedure deleteUser
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`deleteUser`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteUser`(IN`PUser_Id` SMALLINT(20))
BEGIN

DELETE FROM user WHERE User_Id = PUser_Id;

END$$
DELIMITER ;

-- -----------------------------------------------------
-- procedure deleteDepartment
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`deleteDepartment`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `deleteDepartment`(IN`PDepartment_Id` SMALLINT(20))
BEGIN

DELETE FROM department WHERE Department_Id = PDepartment_Id;

END$$
DELIMITER ;
-- -----------------------------------------------------
-- procedure updateUser
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`updateUser`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateUser`( 
IN PUser_Id SMALLINT(20),
IN PUserName VARCHAR(45),
IN PRole_id SMALLINT(6),
IN Pdepartment_id SMALLINT(6)
)

BEGIN

UPDATE user 
SET
UserName=PUserName,
Role_id = PRole_id,
department_id = Pdepartment_id

WHERE PUser_Id = User_Id ;

END$$
DELIMITER ;
-- -----------------------------------------------------
-- procedure updateDepartment
-- -----------------------------------------------------
USE `smartmsph`;
DROP procedure IF EXISTS `smartmsph`.`updateDepartment`;

DELIMITER $$
USE `smartmsph`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `updateDepartment`( 
IN PDepartment_Id SMALLINT(20),
IN PDepartmentName VARCHAR(45),
IN PPerson_Id BIGINT(20) 
)

BEGIN

UPDATE department 
SET
DepartmentName = PDepartmentName,
Person_Id = PPerson_Id
WHERE Department_Id = PDepartment_Id ;

END$$
DELIMITER ;
-- lo de tony


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
